package com.crud.backend.service;
import com.crud.backend.dto.auth.AuthResponse;
import com.crud.backend.dto.auth.LogInRequest;
import com.crud.backend.dto.auth.SignUpRequest;
import com.crud.backend.exception.BadRequestException;
import com.crud.backend.model.User;
import com.crud.backend.repository.UserRepository;
import com.crud.backend.security.JwtService;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

//marks class as service layer component.
//Service contains the core business logic for authentication
//Service receives request from Controller. Service communicates with repository.
@Service
public class AuthService {
    //Service needs access to UserRepository, PasswordEncoder, and JWTService
    //UserRepository -> communicates with the database and automatically makes the necessary SQL code.
    //PasswordEncoder -> Hashes the users password.
    //JwtService -> Provides a unique token for the user for authentication purposes.
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtService jwtService;

    //Gives AuthService access to UserRepository, PasswordEncoder, and JWTService
    public AuthService(UserRepository userRepository, PasswordEncoder passwordEncoder, JwtService jwtService) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.jwtService = jwtService;
    }

    //Creates a new user on sign up and returns a response.
    //Validates if the user already exists in the database before continuing.
    //Takes a SignUpRequest: fullName, email, password.
    public AuthResponse signUp(SignUpRequest request) {
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new BadRequestException("Email is already in use.");
        }

        //Creates a new user and sets values to match request.
        User user = new User();
        user.setFullname(request.getFullname());
        user.setEmail(request.getEmail());
        //encodes the users password
        user.setPassword(passwordEncoder.encode(request.getPassword()));

        //Same thing as User. Used to show that all User key:value pairs have been set.
        User savedUser = userRepository.save(user);

        //Gives the user a token for authentication.
        String token = jwtService.generateToken(savedUser);

        //returns a AuthResponse: id (auto-generated by UserRepository), email, fullName, and token.
        return new AuthResponse(savedUser.getId(), savedUser.getEmail(), savedUser.getFullname(), token);
    }

    //Logs in a user and returns a response.
    //Validates email and password before continuing.
    //Takes a LogInRequest: email and password.
    public AuthResponse logIn(LogInRequest request) {
        User user = userRepository.findByEmail(request.getEmail())
                .orElseThrow(() -> new BadRequestException("Invalid email or password."));

        //Encodes password from request and checks if it matches password in database.
        boolean passwordMatches = passwordEncoder.matches(
                request.getPassword(),
                user.getPassword()
        );

        //If password doesnt match, throw error.
        if (!passwordMatches) {
            throw new BadRequestException("Invalid email or password.");
        }

        //Generates a new token for the user on log in.
        String token = jwtService.generateToken(user);

        //returns an AuthResponse: users id, email, fullName, and token.
        return new AuthResponse(user.getId(), user.getEmail(), user.getFullname(), token);
    }
}
